version: "3.8"

services:
  # web:
  #   build:
  #     context: ..
  #     dockerfile: ./deploy/web/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - core-backend

  core-backend:
    build:
      context: ..
      dockerfile: ./deploy/core-backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/lime_db

  # db:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: lime_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U user -d lime_db"]
  #     interval: 5s
  #     timeout: 5s
  # retries: 5
# volumes:
#   postgres_data:
